//----------------------------------------------------------------------------------------------------
// <auto-generated>
//
//		This code was automatically generated by the UFT Developer Application Model code generator.
//
//		Changes to this file may cause incorrect behavior and will be lost 
//		when the code is regenerated.
//
// </auto-generated>
//----------------------------------------------------------------------------------------------------
using System;
using HP.LFT.SDK;  
using System.Collections.Generic;

namespace AOSFunctionalTests.Application_Areas.Order
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("This class is automatically generated by the UFT Developer Application Model code generator.", "15.01")]
	public class OrderModel : AppModelBase
	{
		#region Constructors

		public OrderModel(ITestObject contextTestObject)
		{
			Name = @"OrderModel";
			RebuildDescriptions();
			
		}

		#endregion

	}
}
